name: Mustafa Bedir Tapkan
bio: ‘Software Engineering Student, who loves Artificial intelligence. ’
picture: 'assets/images/profile.jpg'

url: http://bedirtapkan.me
# your url: http://bedirtapkan.me
permalink: /:title/

analytics: 'UA-MYANALYTICS'
facebook: bedir.tapkan
twitter: BedirTapkan
instagram: bedirtapkan
linkedin: bedirtapkan
github: BedirT
email: bedir.tapkan.53@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
